---
title: "Figures"
author: "Jill Deines"
date: "Friday, December 02, 2016"
output: 
  html_document:
    toc: yes
---

Goal: Make figures of irrigation frequency over the region


```{r knitrOpts, echo=FALSE}
library(knitr)
opts_chunk$set(cache=TRUE, cache.path='cache/4.1_FreqFigs/',
               fig.path='figure/4.1_FreqFigs/')
```

**R Packages Needed**

```{r packages, message=FALSE, echo=TRUE, eval=TRUE}
library(rgdal)
library(raster)
library(grid)
library(colorRamps)
library(fields)
library(RColorBrewer)
```

## Irrigation frequency
Exported raster of years irrigated from 06.6_summaryMaps in GEE

```{r frequencyPrep, eval=FALSE}
# dirs and names
rasDir <- 'C:/Users/deinesji/Google Drive/GEE_classification/RRB_test3_cart_interannualClean'
rasVis <- 'IrrigationFrequencyMap_masked.tif'
rasAll <- 'IrrigationFrequencyMap_0and1neg.tif'

rasEarly <- 'EarliestYearIrrigated_0and1neg.tif'

# load pre-masked, pre-color scaled image
vis <- raster(paste0(rasDir,'/',rasVis))

# load full raster
freq <- raster(paste0(rasDir,'/',rasAll))
freq[freq == -1] <- NA
# write out masked raster
writeRaster(freq, paste0(rasDir,'/IrrigationFrequencyMap_0and1neg_boundMask.tif'))

# load early raster
early <- raster(paste0(rasDir,'/',rasEarly))
early[early == -1] <- NA
early[early == 0] <- 1998

# write out masked raster
writeRaster(early, paste0(rasDir,'/EarliestYearIrrigated_0and1neg_boundMask.tif'))
```

```{r earliestMap_PiYG, fig.width = 6, fig.height=3.5, dpi=96}
rasDir <- 'C:/Users/deinesji/Google Drive/GEE_classification/RRB_test3_cart_interannualClean'
rasEarly <- 'EarliestYearIrrigated_0and1neg_boundMask.tif'

# load full raster
early <- raster(paste0(rasDir,'/',rasEarly))

# palette
colRamp <- c('black',rev(colorRampPalette(brewer.pal(11,'PiYG'))(15)))

spplot(early, col.regions = colRamp, maxpixels = 1000000, colorkey=F)

```


```{r freqMap_matlab2, fig.width = 10, fig.height = 5, dpi=96}
library(grid)
rasDir <- 'C:/Users/deinesji/Google Drive/GEE_classification/RRB_test3_cart_interannualClean'
rasAll <- 'IrrigationFrequencyMap_0and1neg_boundMask.tif'

# load full raster
freq <- raster(paste0(rasDir,'/',rasAll))

# plot scale
scale = list("SpatialPolygonsRescale", layout.scale.bar(), 
  offset = c(-225000,1760000), scale = 100000, fill=c("transparent","black"))
text1 = list("sp.text", c(-220000,1750000), "0")
text2 = list("sp.text", c(-125000,1750000), "100 km")

# color ramp 
matlab <- matlab.like2(15)
spplot(freq, col.regions = c('black',matlab), maxpixels = 2000000,
       par.settings = list(layout.widths=list(right.padding=4.5)),
       sp.layout=list(scale, text1, text2),
       colorkey=list(labels=list(cex=1.2,
                  labels = c(0,2,4,6,8,10,12,14),
                  at = c(-.5,1.5,3.5,5.5,7.5,9.5,11.5,13.5))))


# scale bar legend title
grid.text('Years Irrigated',x=unit(0.975, "npc"),y=unit(0.5, 'npc'), rot=-90, gp=gpar(fontsize=18))
```

```{r freqMap_byr, fig.width = 10, fig.height = 5, dpi=96}
library(grid)
rasDir <- 'C:/Users/deinesji/Google Drive/GEE_classification/RRB_test3_cart_interannualClean'
rasAll <- 'IrrigationFrequencyMap_0and1neg_boundMask.tif'

# load full raster
freq <- raster(paste0(rasDir,'/',rasAll))

# plot scale
scale = list("SpatialPolygonsRescale", layout.scale.bar(), 
  offset = c(-225000,1760000), scale = 100000, fill=c("transparent","black"))
text1 = list("sp.text", c(-220000,1750000), "0")
text2 = list("sp.text", c(-125000,1750000), "100 km")

# color ramp with black for 0, blue:yellow:red for 1-14
palette <- colorRampPalette(c('blue','yellow','red'))(15)
spplot(freq, col.regions = c('black',palette), maxpixels = 2000000,
       par.settings = list(layout.widths=list(right.padding=4.5)),
       sp.layout=list(scale, text1, text2),
       colorkey=list(labels=list(cex=1.2,
                  labels = c(0,2,4,6,8,10,12,14),
                  at = c(-.5,1.5,3.5,5.5,7.5,9.5,11.5,13.5))))


# scale bar legend title
grid.text('Years Irrigated',x=unit(0.975, "npc"),y=unit(0.5, 'npc'), rot=-90, gp=gpar(fontsize=18))
```

```{r byr, fig.width = 8, fig.height = 4}
colRamp <- c('black',colorRampPalette(c('blue','yellow','red'))(15))

plot(1:10)
image.plot(z=0:15,add=F,legend.only=T, nlevel=16,  col=colRamp, 
           horizontal = T,
           smallplot=c(0.1,.9,.93,.98), 
           axis.args=list(at=c(0,2,4,6,8,10,12,14), 
                          labels=as.character(c(0,2,4,6,8,10,12,14))))

```

```{r colorbar_matlab,fig.width = 8, fig.height = 4}
colRamp <- c('black',matlab.like2(15))

plot(1:10)
image.plot(z=0:15,add=F,legend.only=T, nlevel=16,  col=colRamp, 
           horizontal = T,
           smallplot=c(0.1,.9,.93,.98), 
           axis.args=list(at=c(0,2,4,6,8,10,12,14), 
                          labels=as.character(c(0,2,4,6,8,10,12,14))))
```

```{r colorbar_PiYG,fig.width = 5, fig.height = 4}
colRamp <- rev(colorRampPalette(brewer.pal(11,'PiYG'))(14))

plot(1:10)
image.plot(z=0:13,add=F,legend.only=T, nlevel=14,  col=colRamp, 
           horizontal = T,
           smallplot=c(0.1,.9,.93,.98), 
           axis.args=list(at=c(1,3,5,7,9,11,13), 
                          labels=as.character(c(2000,2002,2004,2006,2008,2010,2012))))
```

```{r colorbar_PRGn,fig.width = 5, fig.height = 4}
colRamp <- rev(colorRampPalette(brewer.pal(11,'PRGn'))(14))

plot(1:10)
image.plot(z=0:13,add=F,legend.only=T, nlevel=14,  col=colRamp, 
           horizontal = T,
           smallplot=c(0.1,.9,.93,.98), 
           axis.args=list(at=c(1,3,5,7,9,11,13), 
                          labels=as.character(c(2000,2002,2004,2006,2008,2010,2012))))
```
