---
title: "Irrigation Over Time"
author: "Jill Deines"
date: "December 6, 2016"
output: 
  html_document:
    toc: yes
---

Goal: Investigate trends in irrigated area over time

```{r knitrOpts, echo=FALSE}
library(knitr)
opts_chunk$set(cache=FALSE, 
               fig.path='figure/6.00_irrTrends/')
```

**R Packages Needed**

```{r packages, message=FALSE, echo=TRUE}
library(rgdal)
library(latticeExtra)
library(ggplot2)
library(tidyr)
```

## Load Data
Counts of each class type were tallied for several administrative boundaries in GEE

```{r loadGee}
cellArea <- 30*30 # m^2

regionsDir <- 'C:/Users/deinesji/Google Drive/GEE_tableExports/regionalStats_RRB'

# get filenames
files <- list.files(regionsDir, pattern="*plusAncillary_interannual.csv")

# read in to a single dataframe
all1 = as.data.frame(do.call(rbind, lapply(files, function(x) {
              csv1 <- read.csv(paste0(regionsDir,'/',x))
              csv1$year <- as.numeric(substr(x, start=1,stop=4))
              return(csv1)
            })))

# convert cell count to area
all1$irrigated_m2 <- all1$X1 * cellArea
all1$irrigated_km2 <- all1$irrigated_m2 / 1000000

# find total #cells in the rrcaExtent
all1$totalCells <- all1$X0 + all1$X1 + all1$null
all1[all1$masterID == 'rrcaRrbBuffExtent','totalCells'][1]
```

## Plot Data

### Full RRCA RRB Extent

```{r rrcaExtentPlots, fig.height=2.5}
ggplot(data = all1[all1$masterID == 'rrcaRrbBuffExtent',],
       aes(x = year, y = irrigated_km2)) +
    geom_line() + geom_point() +
    ylab(expression(paste("Irrigated Area (", km^2," )"))) +
    xlab('Year') + ggtitle('Full Region') + 
    theme_bw()
# precip
ggplot(data = all1[all1$masterID == 'rrcaRrbBuffExtent',],
       aes(x = year, y=pr_ann)) +
    geom_line() + geom_point() +
    ylab("Dec - Aug precip  (mm)") +
    xlab('Year') + ggtitle('Full Region') + 
    theme_bw()

# aridity
ggplot(data = all1[all1$masterID == 'rrcaRrbBuffExtent',],
       aes(x = year, y=aridity)) +
    geom_line() + geom_point() +
    ylab("Aridity") +
    xlab('Year') + ggtitle('Full Region') + 
    theme_bw()
```

```{r rrcabyState}

ggplot(data = all1[grepl('full', all1$masterID),],
       aes(x = year, y = irrigated_km2, colour = masterID)) +
    geom_line() + geom_point() +
    ylab(expression(paste("Irrigated Area (", km^2," )"))) +
    xlab('Year') + ggtitle('Full Region by State') +
    theme_bw()
```

### RRB Basin plots

```{r rrbBasinPlots}
ggplot(data = all1[grepl('basin', all1$masterID) &
                     !grepl('NRD', all1$masterID),],
       aes(x = year, y = irrigated_km2, colour = masterID)) +
    geom_line() + geom_point() +
    ylab(expression(paste("Irrigated Area (", km^2," )"))) +
    xlab('Year') + ggtitle('RRB by State') +
   theme_bw() 
```

```{r neBasin, fig.height=2.5}
ggplot(data = all1[grepl('NE_basin', all1$masterID),],
       aes(x = year, y = irrigated_km2)) +
    geom_line() + geom_point() +
    ylab(expression(paste("Irrigated Area (", km^2," )"))) +
    xlab('Year') + ggtitle('Nebraska RRB') +
   theme_bw() 
```
### NRD Basin plots

```{r nrdBasinPlots}
ggplot(data = all1[grepl('NRD', all1$masterID) | 
                     grepl('GMD', all1$masterID),],
       aes(x = year, y = irrigated_km2, colour = masterID)) +
    geom_line() + geom_point() +
    ylab(expression(paste("Irrigated Area (", km^2," )"))) +
    xlab('Year') + ggtitle('By NE NRD') +
   theme_bw() 

```



